[32mINFO    [0m api_log:my_log.py:29 -----正在测试login模块里面第3条测试用例：输入错误的手机号,
[32mINFO    [0m api_log:my_log.py:29 测试数据是：{'mobilephone': '18300070759', 'pwd': '123456'}
[32mINFO    [0m api_log:my_log.py:29 实际结果是:{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
[32mINFO    [0m api_log:my_log.py:29 一条测试用例执行完毕